[package]
name = "raz"
version = "0.5.0-pre"
edition = "2021"
authors = ["Zilezia"]
description = "Bum language in rust (potential next name)"

[features]
default = ["interpreter"]
interpreter = []
compiler = [] # its wip now, only print statements work
